---
# firewall-specific tasks for strongswan

- name: Open firewalld protocols for StrongSwan
  firewalld:
    rich_rule: "rule protocol value={{ item }} accept"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - ah
    - esp
  when:
    (use_firewalld is defined and use_firewalld)

- name: Open firewalld ports for StrongSwan
  firewalld:
    port: "500/udp"
    permanent: true
    state: enabled
    immediate: yes
  when:
    (use_firewalld is defined and use_firewalld)

# - name: "Configure firewall rules to allow strongSwan traffic"
#   ufw:
#     direction=in
#     src="{{ item.0.right.address }}"
#     to="{{ item.0.left.address }}"
#     proto="{{ item.1.proto }}"
#     port="{{ item.1.port | default('') }}"
#     rule=allow
#   when:
#     (use_ufw is defined and use_ufw)
#   with_nested:
#     - "{{ strongswan_conn }}"
#     - [ {"proto": udp, "port": 500}, {"proto": esp}, {"proto": ah} ]
#
# # NOTE: This is a temporary override until the IPSec policy roles are in place,
# #       and requires a patched ufw.py script to allow configuration of GRE
# #       protocols.
# - name: "Configure firewall rules to allow GRE traffic for configured hosts"
#   ufw:
#     direction=in
#     src="{{ item.right.address }}"
#     to="{{ item.left.address }}"
#     proto=gre
#     rule=allow
#   when:
#     (item.left.protoport is defined and item.left.protoport == 47) and
#     (use_ufw is defined and use_ufw)
#   with_items:
#     "{{ strongswan_conn }}"
#   tags:
#     - firewall
