---
# handlers file for strongswan

- name: restart apparmor
  service:
    name=apparmor
    state=restarted
  become: True

- name: restart strongswan
  service:
    name=strongswan
    state=restarted
  become: True
